spring.application.name=urlshortener
# This tells Render to assign a dynamic port, or defaults to 8080 locally
server.port=${PORT:8080}

# FIX: This securely pulls your connection string from the hosting environment
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=nexuslink